from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 1, 2, 1, 1)
        self.map_view_switch = QtWidgets.QComboBox(self.centralwidget)
        self.map_view_switch.setObjectName("map_view_switch")
        self.map_view_switch.addItem("")
        self.gridLayout.addWidget(self.map_view_switch, 1, 4, 1, 1)
        self.mail_button = QtWidgets.QPushButton(self.centralwidget)
        self.mail_button.setObjectName("mail_button")
        self.gridLayout.addWidget(self.mail_button, 3, 0, 1, 1)
        self.search_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.search_bar.setObjectName("search_bar")
        self.gridLayout.addWidget(self.search_bar, 1, 0, 1, 2)
        self.address = QtWidgets.QLabel(self.centralwidget)
        self.address.setObjectName("address")
        self.gridLayout.addWidget(self.address, 3, 1, 1, 2)
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        self.map_label.setObjectName("map_label")
        self.gridLayout.addWidget(self.map_label, 2, 0, 1, 5)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(150, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.collapse_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collapse_btn.sizePolicy().hasHeightForWidth())
        self.collapse_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.collapse_btn.setFont(font)
        self.collapse_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.collapse_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.collapse_btn.setObjectName("collapse_btn")
        self.horizontalLayout_2.addWidget(self.collapse_btn)
        self.close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_2.addWidget(self.close_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(150, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setAutoDefault(False)
        self.reset_button.setDefault(False)
        self.reset_button.setFlat(False)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_3.addWidget(self.reset_button)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_button.setText(_translate("MainWindow", "Искать"))
        self.map_view_switch.setItemText(0, _translate("MainWindow", "переключатель слоёв карты (схема/спутник/гибрид),"))
        self.mail_button.setText(_translate("MainWindow", "ВКЛ/ВЫКЛ (Приписка почтового индекса)"))
        self.address.setText(_translate("MainWindow", "Полный адрес объекта"))
        self.map_label.setText(_translate("MainWindow", "Карта"))
        self.label.setText(_translate("MainWindow", "YaKarta"))
        self.collapse_btn.setText(_translate("MainWindow", " _ "))
        self.close_btn.setText(_translate("MainWindow", " 🗙 "))
        self.reset_button.setText(_translate("MainWindow", "Сброс поискового результата"))
