# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.address = QtWidgets.QLabel(self.centralwidget)
        self.address.setObjectName("address")
        self.gridLayout.addWidget(self.address, 2, 1, 1, 2)
        self.search_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.search_bar.setObjectName("search_bar")
        self.gridLayout.addWidget(self.search_bar, 0, 0, 1, 2)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 0, 2, 1, 1)
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        self.map_label.setObjectName("map_label")
        self.gridLayout.addWidget(self.map_label, 1, 0, 1, 4)
        self.map_view_switch = QtWidgets.QComboBox(self.centralwidget)
        self.map_view_switch.setObjectName("map_view_switch")
        self.map_view_switch.addItem("")
        self.gridLayout.addWidget(self.map_view_switch, 0, 3, 1, 1)
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setObjectName("reset_button")
        self.gridLayout.addWidget(self.reset_button, 2, 3, 1, 1)
        self.mail_button = QtWidgets.QPushButton(self.centralwidget)
        self.mail_button.setObjectName("mail_button")
        self.gridLayout.addWidget(self.mail_button, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.address.setText(_translate("MainWindow", "Полный адрес объекта"))
        self.search_button.setText(_translate("MainWindow", "Искать"))
        self.map_label.setText(_translate("MainWindow", "Карта"))
        self.map_view_switch.setItemText(0, _translate("MainWindow", "переключатель слоёв карты (схема/спутник/гибрид),"))
        self.reset_button.setText(_translate("MainWindow", "Сброс"))
        self.mail_button.setText(_translate("MainWindow", "ВКЛ/ВЫКЛ (Приписка почтового индекса)"))
